# INDIVIDUAL TASK #2

In [5]:
import numpy as np

## PART 1

In [6]:
X = np.array([[4, 2.9], [2.5, 1], [3.5, 4], [2, 2.1]])
X

array([[4. , 2.9],
       [2.5, 1. ],
       [3.5, 4. ],
       [2. , 2.1]])

In [7]:
# Рассчитайте ядерную матрицу
np.linalg.norm(X, ord='nuc')

9.42297301664558

In [8]:
np.linalg.svd(X)

(array([[-0.6022052 , -0.35956138, -0.62267823, -0.34689528],
        [-0.31090722, -0.71286423,  0.58696443,  0.22502011],
        [-0.6447774 ,  0.56403286,  0.44410921, -0.26248056],
        [-0.35347942,  0.21073001, -0.26554018,  0.87185639]]),
 array([8.17008375, 1.25288927]),
 array([[-0.75271794, -0.65834315],
        [-0.65834315,  0.75271794]]))

## PART 2

## PART 3

